### ISSUE TITLE
I'm find a flash filesystem to replace jffs2,can Yaffs2 used on Nor Flash in Linux?

### ISSUE THREAD

**Issue by oska874** [kimushu/yaffs2#1]
We are using a 64MB nor flash in Linux.Currently we are using jffs2, but its start timg is too long.So can Yaffs2 used on Nor Flash in Linux?If so,what should we do.

**Comment by kimushu** [comment]
Hello,
This is an *unofficial* fork. I don't have an expert knowledge for YAFFS2.
Please ask official support (-> https://yaffs.net/support)
